# Generated by Django 3.1.3 on 2020-11-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=255, unique=True, verbose_name='Case ID')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2, verbose_name='Sex')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('ancestry', models.CharField(choices=[('WHT', 'White'), ('HIS', 'Hispanic'), ('BLK', 'Black'), ('AMI', 'American Indian'), ('ASN', 'Asian'), ('PCI', 'Pacific Islander'), ('FIL', 'Filipino'), ('WAS', 'West Asian'), ('ASI', 'Asian Indian')], max_length=4, verbose_name='Ancestry')),
                ('mod', models.CharField(choices=[('ACC', 'accident'), ('SUI', 'suicide'), ('HOM', 'homicide'), ('UND', 'undeterminded')], max_length=4, verbose_name='Mode of Death')),
                ('cod', models.CharField(choices=[('MVC', 'Motor Vehicle Crash'), ('FLL', 'Fall'), ('BFT', 'Blunt Force Trauma'), ('CRS', 'Crush'), ('MAS', 'Mechanical Asphyxia')], max_length=4, verbose_name='Cause of Death')),
                ('cod_type', models.TextField(blank=True, null=True, verbose_name='CoD Info')),
                ('xray', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, verbose_name='X-Ray')),
                ('belted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, verbose_name='Belted')),
                ('obese', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, verbose_name='Obese')),
                ('cardio', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, verbose_name='Cardiovascular Issues')),
                ('patho', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, verbose_name='Pathologies')),
                ('tobacco', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, verbose_name='Cigarette/Tobacco Use')),
                ('marijuana', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, verbose_name='Marijuana Use')),
                ('alcohol', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, verbose_name='Alcohol Use')),
                ('prescription', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, verbose_name='Prescription Medications')),
                ('drug_use', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, verbose_name='Illicit Drug Use')),
                ('health_notes', models.CharField(choices=[('HYP', 'hypertension'), ('CYST', 'cyst'), ('DERM', 'dermititis'), ('HEP', 'hepatomegaly'), ('DEM', 'dementia'), ('CYS', 'cyst'), ('PRO', 'prostate enlargement'), ('MEDS', 'cholestoral meds'), ('OBS', 'obsese'), ('DRG', 'drug use'), ('LIV', 'fatty liver'), ('HRT', 'heart anomaly'), ('HEA', 'healthy'), ('SMO', 'smoker'), ('SUR', 'past surgeries'), ('SUB', 'substance abuse')], max_length=5, verbose_name='Health Notes')),
                ('add_notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
            ],
        ),
    ]
