# Generated by Django 2.2.7 on 2019-11-29 13:46

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pk', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PK')),
                ('case_id', models.CharField(max_length=240, verbose_name='Case ID')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('mod', models.CharField(max_length=240, verbose_name='Mode of Death')),
                ('cod', models.CharField(max_length=240, verbose_name='Cause of Death')),
                ('add_notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
            ],
        ),
    ]
