# Generated by Django 3.1.3 on 2021-01-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fracture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(default='', max_length=240, verbose_name='Case ID')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('sex', models.CharField(max_length=2, verbose_name='Sex')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('ancestry', models.CharField(max_length=20, verbose_name='Ancestry')),
                ('mod', models.CharField(max_length=240, verbose_name='Mode of Death')),
                ('cod', models.CharField(max_length=240, verbose_name='Cause of Death')),
                ('cod_type', models.TextField(blank=True, null=True, verbose_name='CoD Info')),
                ('xray', models.CharField(max_length=1, verbose_name='X-Ray')),
                ('belted', models.CharField(max_length=1, verbose_name='Belted')),
                ('obese', models.CharField(max_length=1, verbose_name='Obese')),
                ('cardio', models.CharField(max_length=1, verbose_name='Cardiovascular Issues')),
                ('patho', models.CharField(max_length=1, verbose_name='Pathologies')),
                ('tobacco', models.CharField(max_length=1, verbose_name='Cigarette/Tobacco Use')),
                ('marijuana', models.CharField(max_length=1, verbose_name='Marijuana Use')),
                ('alcohol', models.CharField(max_length=1, verbose_name='Alcohol Use')),
                ('prescription', models.CharField(max_length=1, verbose_name='Prescription Medications')),
                ('drug_use', models.CharField(max_length=1, verbose_name='Illicit Drug Use')),
                ('health_notes', models.TextField(default=None, verbose_name='Health Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20, verbose_name='Location')),
                ('completeness', models.IntegerField(verbose_name='Completeness')),
                ('fracture_type', models.CharField(max_length=20, verbose_name='Fracture Type')),
                ('cpr', models.CharField(max_length=1, verbose_name='CPR')),
                ('fracture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rib_section', to='patients.fracture')),
            ],
        ),
        migrations.AddField(
            model_name='fracture',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rib_fracture', to='patients.patient'),
        ),
    ]
