# Generated by Django 3.1.3 on 2020-12-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ancestry',
            field=models.CharField(max_length=20, verbose_name='Ancestry'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='case_id',
            field=models.CharField(default='', max_length=240, verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cod',
            field=models.CharField(max_length=240, verbose_name='Cause of Death'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='health_notes',
            field=models.TextField(default=None, verbose_name='Health Notes'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mod',
            field=models.CharField(max_length=240, verbose_name='Mode of Death'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(max_length=2, verbose_name='Sex'),
        ),
    ]
