# Generated by Django 3.1.3 on 2020-11-10 22:01

from django.db import migrations

def create_data(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    #Patient()

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
