# Generated by Django 3.1.5 on 2021-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fil', models.CharField(blank=True, max_length=100, verbose_name='Filter')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Value')),
            ],
        ),
    ]
