# Generated by Django 3.1.3 on 2021-01-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210106_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fracture',
            name='completeness',
            field=models.FloatField(blank=True, null=True, verbose_name='Completeness'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
    ]
