# Generated by Django 3.1.3 on 2020-11-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='add_notes',
            field=models.TextField(default=None, verbose_name='Additional Health Notes'),
        ),
    ]
