# Generated by Django 3.1.3 on 2020-12-02 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20201202_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fracture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, verbose_name='Location')),
                ('completeness', models.IntegerField(verbose_name='Completeness')),
                ('fracture_type', models.CharField(max_length=20, verbose_name='Fracture Type')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
