# Generated by Django 3.1.3 on 2021-01-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20210106_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='Age'),
        ),
    ]
