# Generated by Django 3.1.3 on 2020-12-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_fracture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fracture',
            name='completeness',
        ),
        migrations.RemoveField(
            model_name='fracture',
            name='fracture_type',
        ),
        migrations.AlterField(
            model_name='fracture',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rib_fracture', to='patients.patient'),
        ),
    ]
