# Generated by Django 3.1.3 on 2021-01-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210106_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Age'),
        ),
    ]
