# Generated by Django 3.1.3 on 2020-12-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20201130_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2, verbose_name='Sex'),
        ),
    ]
