# Generated by Django 3.1.3 on 2020-12-28 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20201228_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20, verbose_name='Location')),
                ('completeness', models.IntegerField(verbose_name='Completeness')),
                ('fracture_type', models.CharField(max_length=20, verbose_name='Fracture Type')),
                ('cpr', models.CharField(max_length=1, verbose_name='CPR')),
                ('fracture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rib_section', to='patients.fracture')),
            ],
        ),
    ]
