# Generated by Django 3.1.3 on 2020-12-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20201201_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(max_length=2, verbose_name='Sex'),
        ),
    ]
