# Generated by Django 3.1.3 on 2021-01-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20210107_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fracture',
            name='cpr',
            field=models.CharField(blank=True, max_length=1, verbose_name='CPR'),
        ),
        migrations.AlterField(
            model_name='fracture',
            name='fracture_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fracture Type'),
        ),
        migrations.AlterField(
            model_name='fracture',
            name='location',
            field=models.CharField(blank=True, max_length=20, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alcohol',
            field=models.CharField(blank=True, max_length=1, verbose_name='Alcohol Use'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ancestry',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ancestry'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='belted',
            field=models.CharField(blank=True, max_length=1, verbose_name='Belted'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cardio',
            field=models.CharField(blank=True, max_length=1, verbose_name='Cardiovascular Issues'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cod',
            field=models.CharField(blank=True, max_length=240, verbose_name='Cause of Death'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cpr',
            field=models.CharField(blank=True, max_length=1, verbose_name='CPR'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='drug_use',
            field=models.CharField(blank=True, max_length=1, verbose_name='Illicit Drug Use'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marijuana',
            field=models.CharField(blank=True, max_length=1, verbose_name='Marijuana Use'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mod',
            field=models.CharField(blank=True, max_length=240, verbose_name='Mode of Death'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='obese',
            field=models.CharField(blank=True, max_length=1, verbose_name='Obese'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patho',
            field=models.CharField(blank=True, max_length=1, verbose_name='Pathologies'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.CharField(blank=True, max_length=1, verbose_name='Prescription Medications'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tobacco',
            field=models.CharField(blank=True, max_length=1, verbose_name='Cigarette/Tobacco Use'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='xray',
            field=models.CharField(blank=True, max_length=1, verbose_name='X-Ray'),
        ),
    ]
