# Generated by Django 3.1.2 on 2020-11-03 19:08

from django.db import migrations

def create_data(apps, schema_editor):
    Customer = apps.get_model('patients', 'Patient')
    Customer(first_name="Patient 001", last_name="Patient 001", email="patient001@email.com", phone="00000000", address="Patient 000 Address", description= "Patient 001 description").save()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
